In [1]:
# Dependecies and Setup
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# File to load
high_survey_data = "Clean Attempts High School.csv"
middle_survey_data = "Clean Attempts Middle School.csv"

# Read the High School and Middle Data and store into a Pandas DataFrame
high_data_df = pd.read_csv(high_survey_data)
middle_data_df = pd.read_csv(middle_survey_data)

In [2]:
# Combine the data into a single dataset.
both_df = pd.merge(high_data_df, middle_data_df, on=["year", "year"])
both_df

,year,record_x,age_x,grade_x,consideration_x,plan_x,attempt_x,record_y,age_y,grade_y,consideration_y,plan_y,attempt_y
0,2013,5977,14,9,yes,no,no,86312,14,8,no,no,no
1,2013,5977,14,9,yes,no,no,86313,14,8,no,no,no
2,2013,5977,14,9,yes,no,no,86314,12,7,no,no,no
3,2013,5977,14,9,yes,no,no,86315,14,8,no,no,no
4,2013,5977,14,9,yes,no,no,86316,14,8,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118328878,2019,2159767,18 or older,12,yes,no,yes,110134,14,8,yes,no,no
118328879,2019,2159767,18 or older,12,yes,no,yes,110135,13,8,no,no,no
118328880,2019,2159767,18 or older,12,yes,no,yes,110136,14,8,no,no,no
118328881,2019,2159767,18 or older,12,yes,no,yes,110137,12,6,yes,yes,yes
118328882,2019,2159767,18 or older,12,yes,no,yes,110138,12,6,yes,yes,yes

In [3]:
#Export new dataframe to CSV file
both_df.to_csv("Clean Attempts Both School.csv", encoding='utf-8', index=False)